#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -e

if [ -z $OPENSHIFT_DB_HOST ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc app cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    exit 5
fi

# Confirm database exists, if not create it
if ! /usr/bin/mysql -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" -e "select * from gc_canned_messages;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
then
    echo
    echo "Database schema not found, importing 'database.sql' schema."
    echo
    /usr/bin/mysql -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" "$OPENSHIFT_APP_NAME" < "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/database.sql"
    echo
    echo "done."
    echo "=================================================="
    echo "  GoCart-Admin login: admin@self.mail"
    echo "  GoCart-Admin password: gocartadmin"
	echo "  GoCart-Admin url APPURL/index.php/admin"
	echo "  Don't forget to change your GoCart admin password!"
	echo "  Adapt the Configuration file in the location php/gocart/config/gocart.php to customize GoCart"
	echo "  By default the Application is deployed in Development mode which enables PHP Error Reporting, to deploy as production set ENVIRONMENT in the php/index.php to 'production'"
    echo "=================================================="
else
    echo "Database found, skipping import."
fi